version: '3.7'

services:

  minio:
    image: minio/minio:RELEASE.2022-08-26T19-53-15Z
    volumes:
      - ./miniodata:/data
    ports:
      - "9000:9000"
      # - "9001:9001"
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin # 账号
      MINIO_ROOT_PASSWORD: minioadmin #密码
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server /data --console-address ":9001"
    networks: 
    - lanactions


  distribution:
    image: distribution/distribution:2.8.1
    restart: always
    networks: 
    - lanactions

volumes:
  distribution:
networks:
 lanactions: