ubuntu-rustdesk:
	cd ubuntu-rustdesk
	docker build -t ghcr.io/liangyuanpeng/ubuntu-rustdesk:latest .
	docker push ghcr.io/liangyuanpeng/ubuntu-rustdesk:latest
ubuntu-vnc:
	cd ubuntu-vnc 
	docker build -t ghcr.io/liangyuanpeng/ubuntu-vnc:latest .
	docker push ghcr.io/liangyuanpeng/ubuntu-vnc:latest