
ubuntu_rustdesk:
	cd ubuntu-rustdesk && docker build -t ghcr.io/liangyuanpeng/ubuntu-rustdesk:latest .
	docker push ghcr.io/liangyuanpeng/ubuntu-rustdesk:latest

ubuntu_vnc:
	cd ubuntu-vnc && docker build -t ghcr.io/liangyuanpeng/ubuntu-vnc:latest .
	docker push ghcr.io/liangyuanpeng/ubuntu-vnc:latest

ubuntu_gnome:
	cd ubuntu-gnome && docker build -t ghcr.io/liangyuanpeng/ubuntu-gnome:latest .
	docker push ghcr.io/liangyuanpeng/ubuntu-gnome:latest