name: bot_command
on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        description: 'source ref '
        required: false
        default: "main"
      repo:
        description: 'repo'
        required: false
        default: ""

jobs:

  repush:
    name: repush
    permissions:
      packages: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkoutactions
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: oras push 
        run: |
          COMMIT_MESSAGE=`git log --pretty=format:"%s" -1`
          git commit -s --amend -m $COMMIT_MESSAGE
          git config --global user.email "gcslyp@gmail.com"
          git config --global user.name "Lan Liang"
          git push origin -f
