#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: frpc_ssh
on:
  workflow_dispatch:
    inputs:
      port:
        description: 'port'
        required: true
      initimg:
        description: 'initimg'
        required: false
      timeout:
        description: 'timeout'
        required: false
        default: 120
        type: number 
  # pull_request:

jobs:
  build:
    name: start_frpc
    runs-on: ubuntu-20.04
    steps:
      - name: checkoutactions
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: mv frpc.tar
        run: |
          mv frpc.tar /tmp/frpc.tar

      - uses: oras-project/setup-oras@v1
        with:
          version: 1.0.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.3

      - name: set env
        run: |
          sudo apt update
          sudo apt -y install sshpass
          sudo passwd root << EOD
          root
          root
          EOD
          sudo passwd runner << EOD
          root
          root
          EOD

# TODO install bins:  kubectl/kind/ko...

      - name: run frpc
        run: |
          nohup docker pull kindest/node:v1.25.0 &
          env
          mv /tmp/frpc.tar .
          tar -xvf frpc.tar && cd frpc
          sed -i 's/FRPC_PORT/${{ inputs.port }}/g' frpc.ini
          sed -i 's/FRPC_NAME/github_${{ inputs.port }}/g' frpc.ini
          sed -i 's/FRPC_LOCAL_PORT/${{ secrets.FRPC_LOCAL_PORT }}/g' frpc.ini
          cat frpc.ini
          sed -i 's/FRP_SERVER/${{ secrets.FRP_SERVER_ADDR }}/g' frpc.ini
          sed -i 's/FRP_PORT/${{ secrets.FRP_SERVER_PORT }}/g' frpc.ini
          ./frpc -c frpc.ini