#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: frpc_kind_karmada
on:
  workflow_dispatch:
    inputs:
      port:
        description: 'port'
        required: true
  # pull_request:

jobs:


  frpc:
    name: start_frpc
    runs-on: ubuntu-20.04
    # if: ${{ github.event.workflow_run  }}
    steps:
      - name: checkoutactions
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: mv frpc.tar
        run: |
          mv frpc.tar /tmp/frpc.tar

      - name: set env
        run: |
          sudo apt update
          sudo apt -y install sshpass
          sudo passwd root << EOD
          root
          root
          EOD
          sudo passwd runner << EOD
          root
          root
          EOD

      - name: run frpc
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          nohup docker pull kindest/node:v1.25.0 &
          nohup docker pull ibmcom/curl:4.2.0-f4 &
          mv /tmp/frpc.tar .
          tar -xvf frpc.tar && cd frpc
          cat frpc.ini
          sed -i 's/FRPC_PORT/8227/g' frpc.ini
          sed -i 's/FRPC_NAME/github_8227/g' frpc.ini
          sed -i 's/FRP_SERVER/${{ secrets.FRP_SERVER_ADDR }}/g' frpc.ini
          sed -i 's/FRP_PORT/${{ secrets.FRP_SERVER_PORT }}/g' frpc.ini
          sed -i 's/FRPC_LOCAL_PORT/9443/g' frpc.ini
          cd ..
          sed -i 's/FRP_SERVER/${{ secrets.FRP_SERVER_ADDR }}/g' kind-config
          ./install.sh
          export CLUSTER_HOST=0.0.0.0
          export CLUSTER_NAME=kind
          export KUBECONFIG=/tmp/admin.conf
          ./setup.sh
          touch nohup.out && cat nohup.out
          chmod -R 777 /tmp/admin.conf
          sed -i 's/127.0.0.1/${{ secrets.FRP_SERVER_ADDR }}/g' /tmp/admin.conf
          sed -i 's/9443/8227/g' /tmp/admin.conf


      - name: upload file to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: /tmp/admin.conf
          channel: lanren
          title: kubefile8227

      - name: start frpc 
        run: |
          frpc/frpc -c frpc/frpc.ini

#          docker run --privileged -v /tmp/admin.conf:/tmp/admin.conf -e SLACK_CHANNEL=$SLACK_CHANNEL -e SLACK_TOKEN=$SLACK_TOKEN --rm ibmcom/curl:4.2.0-f4 -F file=@/tmp/admin.conf -F "initial_comment=Hello, Leadville" -F channels=$SLACK_CHANNEL -H "Authorization: Bearer $SLACK_TOKEN" https://slack.com/api/files.upload


#          sed -i 's/FRP_SERVER/${{ secrets.FRP_SERVER_ADDR }}/g' kind-config


 #         nohup  ./frpc -c frpc.ini  &

#          docker login ghcr.io -u liangyuanpeng -p ${{ secrets.TOKEN }}
#          docker run -v $PWD:/tmp -e FILE_PATH=/tmp/fprc/frpc.log ghcr.io/liangyuanpeng/gha:v0.1.0


 #         frpc/frpc -c frpc/frpc.ini

  active:
    name: print
    runs-on: ubuntu-20.04
    steps:
      - name: checkoutactions
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          env
