---
name: Reusable Robustness Workflow
on:
  workflow_call:
    inputs:
      etcdBranch:
        required: true
        type: string
      count:
        required: true
        type: number
      testTimeout:
        required: false
        type: string
        default: '30m'
      artifactName:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: "['ubuntu-latest']"
      scenario:
        required: true
        type: string
      lazyfsEnabled:
        required: true
        type: boolean
permissions: read-all

jobs:
  test:
    timeout-minutes: 210
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          repository: etcd-io/etcd

      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}

      # Temporary monitoring to compare amd64 and arm64 runner performance
      # Refer: https://actuated.dev/blog/right-sizing-vms-github-actions
      - uses: alexellis/setup-arkade@master
      - name: Install vmmeter
        run: |
          sudo -E arkade oci install ghcr.io/openfaasltd/vmmeter:latest --path /usr/local/bin/
      - uses: self-actuated/vmmeter-action@master

      - name: install-lazyfs
        if: ${{ inputs.lazyfsEnabled }}
        run: |
          sudo apt update && sudo apt-get --yes install cmake libfuse3-dev libfuse3-3 fuse3
          sudo sed -i 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf
          make install-lazyfs
      - name: test-robustness
        env:
          ETCD_BRANCH: "${{ inputs.etcdBranch }}"
        run: |
          set -euo pipefail
          go clean -testcache

          GO_TEST_FLAGS="-v --count ${{ inputs.count }} --timeout ${{ inputs.testTimeout }} --run ${{ inputs.scenario }}"
          case "${ETCD_BRANCH}" in
            release-3.5)
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.5
              ;;
            release-3.4)
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.4
              ;;
            main)
              make gofail-enable
              make build
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness
              ;;
            *)
              echo "Failed to find target ${ETCD_BRANCH}"
              exit 1
              ;;
          esac
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: always()
        with:
          name: ${{ inputs.artifactName }}
          path: /tmp/results/*
