on:
  workflow_run:
    workflows: [frpc_pulsar]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  print: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          env
          echo ${{ github.event.workflow_run.conclusion }}